// Code generated by MockGen. DO NOT EDIT.
// Source: trade.go
//
// Generated by this command:
//
//	mockgen -source=trade.go -destination=mock_trade.go -package=workers
//

// Package workers is a generated GoMock package.
package workers
